version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: athena
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306" # 호스트:컨테이너 포트 매핑
    volumes:
      - mysql_data:/var/lib/mysql # 데이터 영속성을 위한 볼륨
    networks:
      - backend_network
    command:
      # MySQL 8.0의 기본 인증 방식 변경
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

  athena:
    build:
      context: ../../athena
      dockerfile: Dockerfile
    container_name: athena
    depends_on:
      - mysql
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/athena
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      KAKAO_API_CID: ${KAKAO_API_CID}
      KAKAO_API_ADMIN_KEY: ${KAKAO_API_ADMIN_KEY}
      KAKAO_API_APPROVAL_URL: ${KAKAO_API_APPROVAL_URL}
      KAKAO_API_CANCEL_URL: ${KAKAO_API_CANCEL_URL}
      KAKAO_API_FAIL_URL: ${KAKAO_API_FAIL_URL}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
    ports:
      - "8080:8080"
    networks:
      - backend_network

volumes:
  mysql_data:
    driver: local

networks:
  backend_network:
    driver: bridge
