spring:

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kakao:
    api:
      cid: ${KAKAO_API_CID}
      admin-key: ${KAKAO_API_ADMIN_KEY}
      approval-url: ${KAKAO_API_APPROVAL_URL}
      cancel-url: ${KAKAO_API_CANCEL_URL}
      fail-url: ${KAKAO_API_FAIL_URL}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}
