spring:

  servlet:
    multipart:
      enabled: true

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kakao:
    api:
      cid: ${KAKAO_API_CID}
      admin-key: ${KAKAO_API_ADMIN_KEY}
      approval-url: ${KAKAO_API_APPROVAL_URL}
      cancel-url: ${KAKAO_API_CANCEL_URL}
      fail-url: ${KAKAO_API_FAIL_URL}

  server:
    forward-headers-strategy: framework
    tomcat:
      remoteip:
        host-header: X-Forwarded-Host
        port-header: X-Forwarded-Port
        protocol-header: X-Forwarded-Proto
        remote-ip-header: X-Forwarded-For
      use-relative-redirects: true

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}

