spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/2pro
    username: yohan
    password: dygks5048
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true