SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE order_item  RESTART IDENTITY;
TRUNCATE TABLE orders  RESTART IDENTITY;
TRUNCATE TABLE product  RESTART IDENTITY;
TRUNCATE TABLE delivery_info  RESTART IDENTITY;
TRUNCATE TABLE project  RESTART IDENTITY;
TRUNCATE TABLE bank_account  RESTART IDENTITY;
TRUNCATE TABLE "user"  RESTART IDENTITY;
TRUNCATE TABLE image_group  RESTART IDENTITY;
TRUNCATE TABLE image  RESTART IDENTITY;
TRUNCATE TABLE coupon  RESTART IDENTITY;

-- IDENTITY 컬럼 초기화 (H2 전용 구문)
--ALTER TABLE order_item ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE orders ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE product ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE delivery_info ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE project ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE bank_account ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE "user" ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE image_group ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE image ALTER COLUMN id RESTART WITH 1;
--ALTER TABLE coupon ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE