SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE order_item RESTART IDENTITY;
TRUNCATE TABLE orders RESTART IDENTITY;
TRUNCATE TABLE product RESTART IDENTITY;
TRUNCATE TABLE delivery_info RESTART IDENTITY;
TRUNCATE TABLE project RESTART IDENTITY;
TRUNCATE TABLE bank_account RESTART IDENTITY;
TRUNCATE TABLE "user" RESTART IDENTITY;
TRUNCATE TABLE image_group RESTART IDENTITY;
TRUNCATE TABLE image RESTART IDENTITY;
TRUNCATE TABLE coupon RESTART IDENTITY;
TRUNCATE TABLE user_coupon RESTART IDENTITY;

-- IDENTITY 컬럼 초기화 (H2 전용 구문)

SET REFERENTIAL_INTEGRITY TRUE