name: Build and Export Docker Image for dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  build:
    runs-on: goormui-MacBookPro-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=dev" $GITHUB_ENV

      - name: Build Docker image and Retag
        run: |
          docker compose --env-file .env build --no-cache
          docker tag athena:latest athena:${IMAGE_TAG}
