name: Build And Deploy Athena Service

on:
  pull_request:
    types: [closed]
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=dev" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          cat <<EOF > infra/docker/.env
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_DRIVER=${{ secrets.DATABASE_DRIVER }}
          KAKAO_API_CID=${{ secrets.KAKAO_API_CID }}
          KAKAO_API_ADMIN_KEY=${{ secrets.KAKAO_API_ADMIN_KEY }}
          KAKAO_API_APPROVAL_URL=${{ secrets.KAKAO_API_APPROVAL_URL }}
          KAKAO_API_CANCEL_URL=${{ secrets.KAKAO_API_CANCEL_URL }}
          KAKAO_API_FAIL_URL=${{ secrets.KAKAO_API_FAIL_URL }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          JWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }}
          ACCESS_KEY=${{ secrets.ACCESS_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          BUCKET_NAME=${{ secrets.BUCKET_NAME }}
          IMAGE_TAG=${{ env.IMAGE_TAG }}
          EOF

      - name: Create Firebase service account JSON
        run: |
          mkdir -p athena/src/main/resources/firebase
          cat <<EOF > athena/src/main/resources/firebase/athena-firebase-config.json
          {
            "type": "service_account",
            "project_id": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "private_key_id": "${{ secrets.FIREBASE_PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.FIREBASE_PRIVATE_KEY }}",
            "client_email": "${{ secrets.FIREBASE_CLIENT_EMAIL }}",
            "client_id": "${{ secrets.FIREBASE_CLIENT_ID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40athena-3b3a8.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
          EOF

      - name: Build via Docker
        run: |
          docker build --no-cache -t docker-athena:${{ env.IMAGE_TAG }} athena

  deploy:
    name: Deploy Athena Service
    runs-on: self-hosted
    environment: dev
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bring up athena container
        run: |
          docker compose -f infra/docker/docker-compose.yml rm -f athena
          docker compose --env-file infra/docker/.env -f infra/docker/docker-compose.yml up -d athena

      - name: Verify service health
        run: |
          docker ps --filter "name=athena" --format "table {{.Names}}\t{{.Status}}"
